name: Back issue
description: Issues relacionados con el back
title: "Back - "
labels: ["back"]
body:
  - type: markdown
    attributes:
      value: |
        Describe el problema relacionado con el devcontainer Docker.
  - type: textarea
    id: details
    attributes:
      label: Detalles
      description: Por favor proporciona detalles del problema.
      placeholder: Describe el problema...
    validations:
      required: true