name: Back issue
description: Issues relacionados con el back
title: "BACK - "
labels: ["back"]
assignees: ["tu-usuario-o-equipo"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: Explica con detalle el objetivo, contexto y alcance funcional.
      placeholder: "Se quiere..."
    validations:
      required: false

  - type: textarea
    id: Requsitos tecnicos
    attributes:
      label: todo
      description: Explica en pasos que se necesita hacer en el issue.
      placeholder: "- [ ] Crear..."
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Aceptance criteria
      description: Explica con detalle lo que se necesita para dar como valido el desarrollo.
      placeholder: "- [ ] Porbar que funciona el.."
    validations:
      required: false