name: Front issue
description: Issues relacionados con el front
title: "Front - "
labels: ["front"]
body:
  - type: markdown
    attributes:
      value: |
        Describe el problema relacionado con el frontend.
  - type: textarea
    id: details
    attributes:
      label: Detalles
      description: Por favor proporciona detalles del problema.
      placeholder: Describe el problema...
    validations:
      required: true